### ISSUE TITLE
Resolve relative URLs when parsing

### ISSUE THREAD

**Issue by aaronpk** [indieweb/microformats-ruby#32]
When parsing a document, all URLs returned should be absolute URLs based off of the URL that is being parsed.

If running Microformats2.parse with a URL as an argument, just use that as the URL to compute relative URLs from. Otherwise, if parsing an HTML string directly, need an additional parameter to pass the URL into.

**Comment by bbauer** [comment]
@aaronpk @tantek and @kylewm sorry for the delay. Looking into this now...

**Comment by veganstraightedge** [comment]
Thanks @bbauer!

**Comment by tantek** [comment]
Yes, what @kylewm said. Updated my plain text comment to escape the tag that should have "just" been displayed. markdown--

**Comment by jeena** [comment]
That would be quite useful for me if this could be fixed too. I haven't seen any other mf2 parser for ruby yet :-/

**Comment by veganstraightedge** [comment]
@jeena Finally merged your PR. I haven't built and released a new gem yet. But if you could build and test it locally to let me know if your PR fixes your problems, I'd appreciate it.

**Comment by dissolve** [comment]
closed accidently, please confirm this looks good

**Comment by dissolve** [comment]
This seems to be pretty well resolved based on some testing i have done. 
Please re-open if there are still issues
