### ISSUE TITLE
Discussion: microformats-ruby logo

### ISSUE THREAD

**Issue by jgarber623** [indieweb/microformats-ruby#78]
As part of #77, I originally introduced a logo for microformats-ruby. It's a derivation of the official logo mark (found on the [Spread Microformats](http://microformats.org/wiki/spread-microformats) wiki page):

<img src="https://raw.githubusercontent.com/gist/jgarber623/5c4cb8712169f51b571d370084006699/raw/d5ece174e46d98770a4e66f313e81e37ee3a5bf0/microformats-ruby-logo.svg?sanitize=true" width="100">

### The Idea

Conceptually, this design marries the microformats logo mark with a color scheme similar to that found throughout the Ruby community. Basically: _everything's red_.

In the course of discussion on #77 (and in IRC/Slack), some licensing issues were brought up. Turns out those aren't an issue as the original author of the logo mark has dedicated it to the public domain, pursuant to the [microformats wiki's licensing](http://microformats.org/wiki/copyright).

### For Discussion

I'm opening this issue to track conversation around the logo:

1. Do we add it to `README.md` as I initially did?
2. Do we create a GitHub Pages site for the gem and use it there?
3. Do we abandon this entirely? (totally fine with me, of course!)

**Comment by dissolve** [comment]
Just to note history of the original
http://microformats.org/wiki/index.php?title=spread-microformats&diff=9819&oldid=9817
later licensing was updated here
http://microformats.org/wiki/index.php?title=spread-microformats&diff=38477&oldid=38322

**Comment by dissolve** [comment]
I think its fine to put it in the README.md, probably put the logo in the repo itself as well, I know your original put it on a gist page
