### ISSUE TITLE
Configure Travis CI / Code Climate coverage reporting

### ISSUE THREAD

**Issue by jgarber623** [indieweb/microformats-ruby#79]
In order to report coverage to Code Climate, someone with access to this project's Code Climate and Travis CI configuration will need to add a `CC_TEST_REPORTER_ID` environment variable. To do that…

1. Navigate to the settings page on Code Climate for microformats-ruby (via https://codeclimate.com/github/indieweb/microformats-ruby). The URLs aren't predictable, but it'll look something like `https://codeclimate.com/repos/<some-long-string>/edit`.
2. Navigate to the "Test Coverage" page (beneath "Analysis" on the left) and grab the "Test Reporter ID" value from that page.
3. Over on Travis Ci, navigate to the settings page (URL should be https://travis-ci.org/indieweb/microformats-ruby/settings).
4. Scroll down to Environment Variables, fill in `CC_TEST_REPORTER_ID` for the name and paste in the value grabbed from Code Climate in step 2.
5. Leave "display value in build log" OFF and click "Add."
6. Cool! Test coverage should be submitted during the next build.

<img width="845" alt="screen shot 2018-01-22 at 10 20 36 am" src="https://user-images.githubusercontent.com/73866/35228172-0c525b72-ff5e-11e7-8316-3c05c808e797.png">

**Comment by veganstraightedge** [comment]
How can I add someone else to the Travis admin? I'd like to hadn't that to @dissolve if possible since he owns this gem these days.

**Comment by jgarber623** [comment]
I'm not familiar with the permissions structure of the GitHub IndieWeb organization since I'm not a member, but @dissolve _might_ have to be an "owner" on the organization. He should then be able to navigate to https://travis-ci.org/profile/indieweb and see the list of organization's GitHub repos.

For example, @FrancisCMS is an organization that I'm an owner of. Here's what I see at https://travis-ci.org/profile/FrancisCMS:

<img width="687" alt="screen shot 2018-01-23 at 8 35 42 am" src="https://user-images.githubusercontent.com/73866/35278697-cca7788e-0018-11e8-81b1-b1494f152791.png">

@dissolve may have to log in to Travis CI (using GitHub auth is the easiest way, if memory serves) and sync his account (top right button in that screenshot) if there've been recent changes to his permissions on organizations.

I _think_ that should do it.

**Comment by dissolve** [comment]
I am already an admin on travis, but not on code climate

**Comment by veganstraightedge** [comment]
If you can point me to where I can add you on Code Climate, I will do it. 👍🏻

**Comment by jgarber623** [comment]
If @dissolve's an owner on the IndieWeb GitHub org (sounds like he is), then he should be able to follow some or all of the steps I uncovered and posted about in IRC/Slack. I captured those over [on the Code Climate wiki page](https://indieweb.org/Code_Climate).

Through some combination of those steps, y'all should be able to navigate to https://codeclimate.com/github/indieweb/microformats-ruby and see a "Settings" navigation option next to "Trends."

How Code Climate handles repos (particularly organization repos) isn't super intuitive…

**Comment by dissolve** [comment]
I'm not an owner of the org, only the repo, thats why code climate isn't letting me in

**Comment by veganstraightedge** [comment]
@dissolve  Hmm. Maybe @aaronpk or someone else can help by making you an owner or by doing the Code Climate set up for you.

**Comment by aaronpk** [comment]
I don't see a settings option on Code Climate. I even authorized it with my github account.

![screenshot 2018-01-29 10 26 59](https://user-images.githubusercontent.com/113001/35527246-f8a96ec2-04de-11e8-8b25-e64a65e02772.png)

**Comment by aaronpk** [comment]
Code Climate doesn't even show me any indieweb repos when I try to go and add one.

**Comment by aaronpk** [comment]
aha... figured it out. I had to go back and re-sync Code Climate after adding my github authorization. *now* I see the code climate settings button.

**Comment by aaronpk** [comment]
okay i just did the whole thing at the top adding the token to travis. I guess it's done? I don't see the little badge updated tho.

**Comment by jgarber623** [comment]
@aaronpk Awesome, thanks! The next time Travis CI does a build, it _should_ kick off test coverage reports to Code Climate. Presuming that goes well, the badge will be updated.

**Comment by dissolve** [comment]
I have a branch where I have been working on test coverage and have already found some unreachable code because of it.  Could merge that in to run it through a test

**Comment by jgarber623** [comment]
This appears to be working as intended. Closing!
